// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_qnXvvyL1pj7bjhjuieh5kUwCMOFnx4',
    appId: '1:681272485947:web:2d45a72544ef6a1d35141e',
    messagingSenderId: '681272485947',
    projectId: 'ai-otc-prototype',
    authDomain: 'ai-otc-prototype.firebaseapp.com',
    storageBucket: 'ai-otc-prototype.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmr8F685synbco9-9iBSAilRidEwd-5AA',
    appId: '1:681272485947:android:d7168716eac32ee935141e',
    messagingSenderId: '681272485947',
    projectId: 'ai-otc-prototype',
    storageBucket: 'ai-otc-prototype.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJUdFEm0TCb1p6cfbyvnzETPGvlFrZNs',
    appId: '1:681272485947:ios:5272baa37997d26835141e',
    messagingSenderId: '681272485947',
    projectId: 'ai-otc-prototype',
    storageBucket: 'ai-otc-prototype.firebasestorage.app',
    iosBundleId: 'com.example.hellohackersFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJUdFEm0TCb1p6cfbyvnzETPGvlFrZNs',
    appId: '1:681272485947:ios:5272baa37997d26835141e',
    messagingSenderId: '681272485947',
    projectId: 'ai-otc-prototype',
    storageBucket: 'ai-otc-prototype.firebasestorage.app',
    iosBundleId: 'com.example.hellohackersFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn_qnXvvyL1pj7bjhjuieh5kUwCMOFnx4',
    appId: '1:681272485947:web:117676a930460e6b35141e',
    messagingSenderId: '681272485947',
    projectId: 'ai-otc-prototype',
    authDomain: 'ai-otc-prototype.firebaseapp.com',
    storageBucket: 'ai-otc-prototype.firebasestorage.app',
  );

}